#                                                Task 3

## Importing Libraries

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Load Dataset

In [16]:
df = pd.read_csv('Round1_Problem2-of-3_Dataset.csv')
df.head()

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274.0,...,5.0,0.0,1.0,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0.0,...,42.0,0.0,8.0,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767.0,...,38.0,0.0,2.0,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0.0,...,65.0,0.0,7.0,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,02/03/11,Employed,M,43836.0,...,44.0,0.0,1.0,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize

In [17]:
print(df.dtypes)

Customer                          object
State                             object
Customer Lifetime Value          float64
Response                          object
Coverage                          object
Education                         object
Effective To Date                 object
EmploymentStatus                  object
Gender                            object
Income                           float64
Location Code                     object
Marital Status                    object
Monthly Premium Auto             float64
Months Since Last Claim          float64
Months Since Policy Inception    float64
Number of Open Complaints        float64
Number of Policies               float64
Policy Type                       object
Policy                            object
Renew Offer Type                  object
Sales Channel                     object
Total Claim Amount               float64
Vehicle Class                     object
Vehicle Size                      object
dtype: object

In [18]:
df['Marital Status'].value_counts() # Total Married and Single values

Married     4818
Single      2225
Divorced    1250
Name: Marital Status, dtype: int64

In [19]:
### type your answer here
df1 = df.sort_values(by='Income', ascending=False, axis=0, inplace=True)
df1 = df[0:5]
df1

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
1750,CJ31839,California,2859.528930,No,Basic,Bachelor,2/18/11,Employed,M,99981.0,...,22.0,0.0,1.0,Special Auto,Special L2,Offer2,Web,204.872273,Four-Door Car,Small
2306,GL69461,Oregon,2628.468543,No,Basic,College,2/16/11,Employed,F,99961.0,...,54.0,2.0,1.0,Personal Auto,Personal L1,Offer3,Agent,316.800000,Four-Door Car,Medsize
532,JS42382,Oregon,6172.914199,No,Extended,Master,1/27/11,Employed,M,99960.0,...,83.0,0.0,4.0,Corporate Auto,Corporate L3,Offer1,Agent,364.800000,Four-Door Car,Small
932,ST43550,Oregon,5727.327124,No,Basic,Bachelor,1/26/11,Employed,M,99934.0,...,12.0,0.0,3.0,Special Auto,Special L3,Offer4,Web,460.323855,Four-Door Car,Medsize
4811,GA27295,California,39365.296160,No,Basic,Master,1/14/11,Employed,F,99875.0,...,37.0,0.0,2.0,Personal Auto,Personal L3,Offer3,Call Center,114.972914,SUV,Medsize

### Married customers

In [20]:
married = df[df['Marital Status']=='Married']
married.sort_values(by='Income', ascending=False, axis=0, inplace=True)
married

C:\Users\dipes\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
1750,CJ31839,California,2859.528930,No,Basic,Bachelor,2/18/11,Employed,M,99981.0,...,22.0,0.0,1.0,Special Auto,Special L2,Offer2,Web,204.872273,Four-Door Car,Small
2306,GL69461,Oregon,2628.468543,No,Basic,College,2/16/11,Employed,F,99961.0,...,54.0,2.0,1.0,Personal Auto,Personal L1,Offer3,Agent,316.800000,Four-Door Car,Medsize
532,JS42382,Oregon,6172.914199,No,Extended,Master,1/27/11,Employed,M,99960.0,...,83.0,0.0,4.0,Corporate Auto,Corporate L3,Offer1,Agent,364.800000,Four-Door Car,Small
932,ST43550,Oregon,5727.327124,No,Basic,Bachelor,1/26/11,Employed,M,99934.0,...,12.0,0.0,3.0,Special Auto,Special L3,Offer4,Web,460.323855,Four-Door Car,Medsize
5856,IN15077,California,4807.846463,No,Basic,High School or Below,01/04/11,Employed,M,99874.0,...,42.0,0.0,1.0,Corporate Auto,Corporate L2,Offer2,Call Center,307.639408,Sports Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3061,RL97327,Washington,4060.956163,No,Premium,Bachelor,1/17/11,Unemployed,M,0.0,...,30.0,1.0,1.0,Personal Auto,Personal L2,Offer2,Call Center,699.823461,Four-Door Car,Medsize
4793,PL88841,Arizona,4228.734374,No,Basic,Bachelor,01/12/11,Unemployed,M,0.0,...,82.0,2.0,8.0,Corporate Auto,Corporate L2,Offer2,Agent,302.400000,Two-Door Car,Small
3057,VU18023,California,7780.903354,No,Basic,High School or Below,1/28/11,Unemployed,F,0.0,...,93.0,0.0,2.0,Personal Auto,Personal L1,Offer3,Call Center,504.000000,Four-Door Car,Small
3053,RK45396,California,5380.316469,No,Basic,Bachelor,02/01/11,Unemployed,M,0.0,...,95.0,0.0,3.0,Corporate Auto,Corporate L2,Offer2,Web,350.400000,Four-Door Car,Medsize
5828,AY35050,Arizona,7292.913911,No,Extended,College,2/23/11,Unemployed,F,0.0,...,70.0,0.0,8.0,Personal Auto,Personal L3,Offer1,Branch,470.400000,Two-Door Car,Medsize

In [21]:
married.shape

(4818, 24)

#### Married customers by income with medsize vehicle size with total claim amount is greater than &200 with less than two policies.

In [22]:
married_people = married[(married['Vehicle Size']=='Medsize') & (married['Total Claim Amount'] > 200) & (married['Number of Policies'] < 2)]

In [23]:
married_people

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
2306,GL69461,Oregon,2628.468543,No,Basic,College,2/16/11,Employed,F,99961.0,...,54.0,2.0,1.0,Personal Auto,Personal L1,Offer3,Agent,316.800000,Four-Door Car,Medsize
5856,IN15077,California,4807.846463,No,Basic,High School or Below,01/04/11,Employed,M,99874.0,...,42.0,0.0,1.0,Corporate Auto,Corporate L2,Offer2,Call Center,307.639408,Sports Car,Medsize
4643,FG47217,California,2538.857089,No,Basic,Bachelor,02/11/11,Employed,M,99824.0,...,56.0,0.0,1.0,Special Auto,Special L2,Offer1,Agent,302.400000,Four-Door Car,Medsize
1772,QF21045,Oregon,2735.538859,No,Basic,College,2/14/11,Employed,F,99205.0,...,21.0,0.0,1.0,Personal Auto,Personal L2,Offer2,Branch,323.246017,Two-Door Car,Medsize
1081,KC71643,Oregon,2463.236825,No,Basic,High School or Below,1/17/11,Employed,M,99144.0,...,51.0,0.0,1.0,Corporate Auto,Corporate L2,Offer2,Call Center,292.800000,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3159,YK93229,Oregon,3260.744760,No,Extended,High School or Below,1/18/11,Unemployed,M,0.0,...,33.0,0.0,1.0,Personal Auto,Personal L3,Offer2,Call Center,432.000000,Two-Door Car,Medsize
3219,WX48434,Arizona,4270.034394,Yes,Extended,College,1/19/11,Unemployed,M,0.0,...,2.0,0.0,1.0,Corporate Auto,Corporate L3,Offer2,Agent,725.870693,SUV,Medsize
3006,CW98845,Oregon,2316.796105,No,Basic,Bachelor,2/24/11,Unemployed,M,0.0,...,80.0,0.0,1.0,Personal Auto,Personal L2,Offer4,Branch,307.200000,Four-Door Car,Medsize
3003,ZZ31825,Oregon,2519.918897,No,Basic,Bachelor,1/25/11,Unemployed,M,0.0,...,26.0,0.0,1.0,Personal Auto,Personal L2,Offer2,Branch,482.400000,Four-Door Car,Medsize
3061,RL97327,Washington,4060.956163,No,Premium,Bachelor,1/17/11,Unemployed,M,0.0,...,30.0,1.0,1.0,Personal Auto,Personal L2,Offer2,Call Center,699.823461,Four-Door Car,Medsize

#### Indexing Married people whose Marital Status is Married

In [24]:
married_people.set_index('Marital Status', inplace=True)
married_people

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
Marital Status,,,,,,,,,,,,,,,,,,,,,
Married,GL69461,Oregon,2628.468543,No,Basic,College,2/16/11,Employed,F,99961.0,...,54.0,2.0,1.0,Personal Auto,Personal L1,Offer3,Agent,316.800000,Four-Door Car,Medsize
Married,IN15077,California,4807.846463,No,Basic,High School or Below,01/04/11,Employed,M,99874.0,...,42.0,0.0,1.0,Corporate Auto,Corporate L2,Offer2,Call Center,307.639408,Sports Car,Medsize
Married,FG47217,California,2538.857089,No,Basic,Bachelor,02/11/11,Employed,M,99824.0,...,56.0,0.0,1.0,Special Auto,Special L2,Offer1,Agent,302.400000,Four-Door Car,Medsize
Married,QF21045,Oregon,2735.538859,No,Basic,College,2/14/11,Employed,F,99205.0,...,21.0,0.0,1.0,Personal Auto,Personal L2,Offer2,Branch,323.246017,Two-Door Car,Medsize
Married,KC71643,Oregon,2463.236825,No,Basic,High School or Below,1/17/11,Employed,M,99144.0,...,51.0,0.0,1.0,Corporate Auto,Corporate L2,Offer2,Call Center,292.800000,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Married,YK93229,Oregon,3260.744760,No,Extended,High School or Below,1/18/11,Unemployed,M,0.0,...,33.0,0.0,1.0,Personal Auto,Personal L3,Offer2,Call Center,432.000000,Two-Door Car,Medsize
Married,WX48434,Arizona,4270.034394,Yes,Extended,College,1/19/11,Unemployed,M,0.0,...,2.0,0.0,1.0,Corporate Auto,Corporate L3,Offer2,Agent,725.870693,SUV,Medsize
Married,CW98845,Oregon,2316.796105,No,Basic,Bachelor,2/24/11,Unemployed,M,0.0,...,80.0,0.0,1.0,Personal Auto,Personal L2,Offer4,Branch,307.200000,Four-Door Car,Medsize
Married,ZZ31825,Oregon,2519.918897,No,Basic,Bachelor,1/25/11,Unemployed,M,0.0,...,26.0,0.0,1.0,Personal Auto,Personal L2,Offer2,Branch,482.400000,Four-Door Car,Medsize
Married,RL97327,Washington,4060.956163,No,Premium,Bachelor,1/17/11,Unemployed,M,0.0,...,30.0,1.0,1.0,Personal Auto,Personal L2,Offer2,Call Center,699.823461,Four-Door Car,Medsize

## Single customers

In [25]:
Single = df[df['Marital Status']=='Single']
Single.sort_values(by='Income', ascending=False, axis=0, inplace=True)
Single

C:\Users\dipes\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
4953,LQ79472,Arizona,3423.822189,No,Extended,College,1/17/11,Employed,M,99816.0,...,0.0,0.0,1.0,Corporate Auto,Corporate L2,Offer3,Branch,172.913031,Two-Door Car,Medsize
2038,ER19995,Washington,17786.277800,No,Basic,College,1/22/11,Employed,F,99790.0,...,8.0,0.0,2.0,Personal Auto,Personal L3,Offer3,Call Center,178.986788,Four-Door Car,Medsize
5807,CR85257,Oregon,4996.545123,No,Basic,High School or Below,02/05/11,Employed,M,99761.0,...,73.0,0.0,3.0,Corporate Auto,Corporate L3,Offer2,Branch,452.246664,Two-Door Car,Medsize
4158,WE68750,Oregon,5687.897911,No,Basic,Bachelor,1/24/11,Employed,M,99747.0,...,87.0,0.0,5.0,Corporate Auto,Corporate L2,Offer1,Call Center,61.536107,Two-Door Car,Medsize
2221,VD51297,California,7320.988240,No,Basic,College,01/09/11,Employed,M,99722.0,...,48.0,0.0,2.0,Personal Auto,Personal L3,Offer4,Call Center,292.800000,Four-Door Car,Small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2986,YN19139,Nevada,2558.762931,No,Basic,High School or Below,01/11/11,Unemployed,M,0.0,...,14.0,0.0,1.0,Corporate Auto,Corporate L3,Offer2,Agent,518.400000,Four-Door Car,Medsize
2992,GJ70481,Arizona,4428.038374,No,Basic,High School or Below,01/03/11,Unemployed,M,0.0,...,47.0,0.0,8.0,Personal Auto,Personal L3,Offer3,Agent,628.801638,Four-Door Car,Small
3027,TC81636,Arizona,10196.110600,No,Basic,High School or Below,01/07/11,Unemployed,M,0.0,...,75.0,0.0,2.0,Corporate Auto,Corporate L3,Offer4,Web,720.000000,SUV,Medsize
3028,IC55961,Arizona,20552.621280,No,Basic,High School or Below,1/26/11,Unemployed,F,0.0,...,97.0,1.0,2.0,Corporate Auto,Corporate L2,Offer1,Agent,1430.336183,Luxury SUV,Medsize
8292,WO42164,Oregon,6465.223746,No,Extended,High School or Below,02/07/11,Unemployed,M,0.0,...,24.0,0.0,3.0,Personal Auto,Personal L3,Offer1,Call Center,662.400000,Four-Door Car,Medsize

In [26]:
Single.shape

(2225, 24)

#### Single customers by income with medsize vehicle size with total claim amount is greater than &200 with less than two policies.

In [27]:
Single_people = Single[(Single['Vehicle Size']=='Medsize') & (Single['Total Claim Amount'] > 200) & (Single['Number of Policies'] < 2)]

In [28]:
Single_people

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
186,UF46533,California,4574.524094,No,Basic,College,1/30/11,Employed,F,99316.0,...,53.0,0.0,1.0,Corporate Auto,Corporate L3,Offer2,Branch,754.358929,SUV,Medsize
3089,LM86393,Oregon,2828.095211,No,Basic,High School or Below,1/19/11,Employed,F,98680.0,...,38.0,2.0,1.0,Personal Auto,Personal L3,Offer2,Call Center,345.600000,Four-Door Car,Medsize
4414,FT74388,Nevada,4623.624811,No,Basic,High School or Below,1/19/11,Employed,M,97065.0,...,0.0,0.0,1.0,Personal Auto,Personal L2,Offer4,Branch,561.600000,SUV,Medsize
1954,SK46419,California,4072.849436,No,Basic,High School or Below,1/31/11,Employed,M,96443.0,...,17.0,0.0,1.0,Personal Auto,Personal L3,Offer4,Branch,489.600000,SUV,Medsize
3291,IK12576,Oregon,4233.568780,No,Premium,Bachelor,2/13/11,Employed,F,95647.0,...,30.0,0.0,1.0,Personal Auto,Personal L2,Offer1,Agent,508.800000,Two-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3020,GT66241,California,2414.072446,No,Basic,High School or Below,01/08/11,Unemployed,M,0.0,...,30.0,0.0,1.0,Personal Auto,Personal L3,Offer2,Call Center,511.200000,Four-Door Car,Medsize
3005,HI16452,Oregon,3028.780121,No,Extended,High School or Below,02/01/11,Unemployed,M,0.0,...,52.0,1.0,1.0,Special Auto,Special L3,Offer1,Branch,483.881752,Four-Door Car,Medsize
4936,UY57856,Oregon,2987.949471,No,Extended,College,2/27/11,Unemployed,F,0.0,...,22.0,0.0,1.0,Corporate Auto,Corporate L2,Offer3,Branch,708.693556,Four-Door Car,Medsize
4931,NM91640,Oregon,2442.216651,No,Basic,High School or Below,01/07/11,Unemployed,M,0.0,...,9.0,3.0,1.0,Personal Auto,Personal L1,Offer4,Branch,532.800000,Four-Door Car,Medsize
2986,YN19139,Nevada,2558.762931,No,Basic,High School or Below,01/11/11,Unemployed,M,0.0,...,14.0,0.0,1.0,Corporate Auto,Corporate L3,Offer2,Agent,518.400000,Four-Door Car,Medsize

### Indexing Single people whose Marital Status is Married

In [29]:
Single_people.set_index('Marital Status', inplace=True)
Single_people

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
Marital Status,,,,,,,,,,,,,,,,,,,,,
Single,UF46533,California,4574.524094,No,Basic,College,1/30/11,Employed,F,99316.0,...,53.0,0.0,1.0,Corporate Auto,Corporate L3,Offer2,Branch,754.358929,SUV,Medsize
Single,LM86393,Oregon,2828.095211,No,Basic,High School or Below,1/19/11,Employed,F,98680.0,...,38.0,2.0,1.0,Personal Auto,Personal L3,Offer2,Call Center,345.600000,Four-Door Car,Medsize
Single,FT74388,Nevada,4623.624811,No,Basic,High School or Below,1/19/11,Employed,M,97065.0,...,0.0,0.0,1.0,Personal Auto,Personal L2,Offer4,Branch,561.600000,SUV,Medsize
Single,SK46419,California,4072.849436,No,Basic,High School or Below,1/31/11,Employed,M,96443.0,...,17.0,0.0,1.0,Personal Auto,Personal L3,Offer4,Branch,489.600000,SUV,Medsize
Single,IK12576,Oregon,4233.568780,No,Premium,Bachelor,2/13/11,Employed,F,95647.0,...,30.0,0.0,1.0,Personal Auto,Personal L2,Offer1,Agent,508.800000,Two-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Single,GT66241,California,2414.072446,No,Basic,High School or Below,01/08/11,Unemployed,M,0.0,...,30.0,0.0,1.0,Personal Auto,Personal L3,Offer2,Call Center,511.200000,Four-Door Car,Medsize
Single,HI16452,Oregon,3028.780121,No,Extended,High School or Below,02/01/11,Unemployed,M,0.0,...,52.0,1.0,1.0,Special Auto,Special L3,Offer1,Branch,483.881752,Four-Door Car,Medsize
Single,UY57856,Oregon,2987.949471,No,Extended,College,2/27/11,Unemployed,F,0.0,...,22.0,0.0,1.0,Corporate Auto,Corporate L2,Offer3,Branch,708.693556,Four-Door Car,Medsize
Single,NM91640,Oregon,2442.216651,No,Basic,High School or Below,01/07/11,Unemployed,M,0.0,...,9.0,3.0,1.0,Personal Auto,Personal L1,Offer4,Branch,532.800000,Four-Door Car,Medsize
Single,YN19139,Nevada,2558.762931,No,Basic,High School or Below,01/11/11,Unemployed,M,0.0,...,14.0,0.0,1.0,Corporate Auto,Corporate L3,Offer2,Agent,518.400000,Four-Door Car,Medsize

## Thank You